CREATE TABLE IF NOT EXISTS services(
  id INT NOT NULL AUTO_INCREMENT,
  url VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('OK', 'FAIL'),
  PRIMARY KEY (id)
);
